import os
from datetime import date
from discord.ext import commands

import discord
from dotenv import load_dotenv

days = [31, 28, 31, 30, 31, 30,
        31, 31, 30, 31, 30, 31]

themes = [
    "Happiness",
    "Beauty",
    "Sleep",
    "Garden",
    "Imagination",
    "Secret",
    "Give",
    "Thankful",
    "Kindness",
    "Inside",
    "Outside",
    "Jump",
    "Friendship",
    "Love",
    "Fire",
    "Light",
    "Darkness",
    "Dream",
    "Believe",
    "Hope",
    "Faith",
    "Focus",
    "Clean",
    "Angry",
    "Work",
    "Music",
    "Stars",
    "Mystery",
    "Envelope",
    "Book",
    "Dare",
    "Choose",
    "Beach",
    "Forgiveness",
    "Disaster",
    "Dance",
    "Mistake",
    "New",
    "Yes",
    "Path",
    "Horizon",
    "Mountain",
    "River",
    "Open",
    "Heart",
    "Soul",
    "Tear",
    "Spiral",
    "Up",
    "Go",
    "Be",
    "Seek",
    "Learn",
    "Balance",
    "Grow",
    "Strength",
    "Seek",
    "Passion",
    "Move",
    "Today",
    "Awaken",
    "Angels",
    "Laughter",
    "Listening",
    "Pause",
    "Peace",
    "Relax",
    "Space",
    "Wisdom",
    "Difference",
    "Begin",
    "Time",
    "Brave",
    "Breathe",
    "Childhood",
    "Discovery",
    "Mind",
    "Energy",
    "Flower",
    "Health",
    "Harmony",
    "Recovery",
    "Stand",
    "Nowhere",
    "Soar",
    "Skip",
    "Fresh",
    "Delicious",
    "Power",
    "Complete",
    "Grace",
    "Legend",
    "Ecstasy",
    "Hug",
    "Proud",
    "Simple",
    "Machine",
    "Victory",
    "Vibrancy",
    "Leadership",
    "Alive",
    "Bloom",
    "Fame",
    "Enormous",
    "Independent",
    "Unique",
    "Metamorphosis",
    "Silence",
    "Tranquility",
    "Project",
    "Smile",
    "Miracle",
    "Amazing",
    "Game",
    "Connected",
    "Muse",
    "Dazzle",
    "Determination",
    "Free",
    "Help",
    "Intuition",
    "Smart",
    "Sweet",
    "Honesty",
    "Useful",
    "Safety",
    "Ready",
    "Vision",
    "Cycle",
    "Discipline",
    "Promise",
    "Patience",
    "Destiny",
    "Rejuvenate",
    "Shine",
    "Talk",
    "Stress",
    "Missing",
    "Age",
    "Success",
    "Motivation",
    "Family",
    "Loneliness",
    "Experience",
    "Future",
    "Vintage",
    "Wings",
    "Letter",
    "Wandering",
    "Factory",
    "Rainbow",
    "Ask",
    "Self",
    "Locket",
    "Home",
    "Cloud",
    "Hunger",
    "Possibilities",
    "Boredom",
    "Innocence",
    "Charge",
    "Rhythm",
    "Date",
    "Consequence",
    "Prescription",
    "Goals",
    "Lost",
    "Found",
    "Cry",
    "Parade",
    "Party",
    "Ice",
    "Dragon",
    "Alarm",
    "Understanding",
    "Uncomfortable",
    "Serious",
    "Opposites",
    "Playful",
    "Attention",
    "Caring",
    "Hero",
    "Lace",
    "Clue",
    "Ideas",
    "Junk",
    "Collection",
    "Radio",
    "Interview",
    "Zoom",
    "Puzzle",
    "Landscape",
    "Advice",
    "Memories",
    "Communication",
    "Compassion",
    "Universe",
    "Loyalty",
    "Sharing",
    "Travel",
    "Voices",
    "Sidewalk",
    "Tree",
    "Story",
    "Why",
    "Maybe",
    "Antique",
    "Action",
    "Culture",
    "Fuel",
    "Desire",
    "Weather",
    "Directions",
    "List",
    "Ride",
    "Wish",
    "Breakfast",
    "Touch",
    "Sadness",
    "Comfort",
    "Circle",
    "Reﬂection",
    "Optimism",
    "Anxiety",
    "Shadow",
    "Spirit",
    "Stretch",
    "Challenge",
    "Five",
    "Messy",
    "Adventure",
    "Fun",
    "Surprise",
    "Illusion",
    "Mischief",
    "Shy",
    "Lesson",
    "Whisper",
    "Fight",
    "Castle",
    "Protect",
    "Shop",
    "Wheel",
    "Pieces",
    "Leaves",
    "Fool",
    "Productivity",
    "Overcome",
    "Encouragement",
    "Watch",
    "Lighthouse",
    "Mild",
    "Mouth",
    "Rare",
    "Target",
    "Boat",
    "Box",
    "Grief",
    "Heavy",
    "Zeal",
    "Color",
    "Brilliance",
    "Enthusiastic",
    "Approval",
    "Enchanting",
    "Attraction",
    "Photograph",
    "Waterfall",
    "Moment",
    "Paradise",
    "Parachute",
    "Social",
    "Zingy",
    "Number",
    "Little",
    "Sound",
    "Reach",
    "Money",
    "Staircase",
    "Lemon",
    "Wood",
    "Try",
    "You",
    "Quote",
    "Weakness",
    "Bridge",
    "Building",
    "Clothes",
    "Prepare",
    "Teach",
    "Window",
    "Drive",
    "Middle",
    "Microphone",
    "Deﬁnition",
    "Shout",
    "Catch",
    "Release",
    "Balloons",
    "Sharp",
    "Crowd",
    "Cute",
    "Cheery",
    "Glow",
    "Apple",
    "Pictures",
    "Swing",
    "Wave",
    "Joke",
    "Cope",
    "Accomplish",
    "Special",
    "Neighborhood",
    "Wonderful",
    "Service",
    "Calling",
    "Magic",
    "Spontaneous",
    "Fluffy",
    "Organic",
    "Silly",
    "Thunderstorm",
    "Toys",
    "Butterﬂy",
    "Buzz",
    "Vine",
    "Shock",
    "Enjoy",
    "Craving",
    "Respect",
    "Abstract",
    "Rainbow",
    "Train",
    "Invention",
    "Perspective",
    "Genius",
    "Circus",
    "Ball",
    "Crystal",
    "Fairy",
    "Cup",
    "Reality",
    "Forget",
    "Priorities",
    "Journey",
    "Hands",
    "Shoes",
    "Television",
    "Newspaper",
    "Radiance",
    "Hidden",
    "Fright",
    "Climb",
    "Guess",
    "Pretend",
    "Turn",
    "Shatter",
    "Together",
    "Adapt",
    "Keep",
    "Closed",
    "Embrace",
    "Blessing",
    "Block",
    "Pizzazz",
    "Breakthrough",
    "Curiosity",
    "Distance",
    "Zen"]

load_dotenv()
intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix='!', intents=intents)
TOKEN = os.getenv('DISCORD_TOKEN')


@bot.command()
async def ping(ctx):
    await ctx.send('pong')


@bot.command()
async def today(ctx):
    index = get_day_of_year() - 1
    response = 'Today\'s theme is ✨' + themes[index] + '✨'
    await ctx.send(response)


@bot.command()
async def yesterday(ctx):
    index = get_day_of_year() - 2
    response = 'Yesterday\'s theme was ✨' + themes[index] + '✨'
    await ctx.send(response)


@bot.command()
async def tomorrow(ctx):
    index = get_day_of_year()
    response = 'Tomorrow\'s theme will be ✨' + themes[index] + '✨'
    await ctx.send(response)


@bot.command()
async def fuckyou(ctx):
    await ctx.send("NO FUCK YOU!")


@bot.command()
async def highfive(ctx):
    await ctx.send("🙏")


@bot.command()
async def loveyou(ctx):
    await ctx.send("❤️")

@bot.command()
async def blessyou(ctx):
    await ctx.send("God's not real, we're all alone out here")

def get_day_of_year():
    today_date = date.today()
    year = today_date.year
    month = today_date.month
    day = today_date.day

    # If current year is a leap year and the date
    # given is after the 28th of February then
    # it must include the 29th February
    if (month > 2 and year % 4 == 0 and
            (year % 100 != 0 or year % 400 == 0)):
        day += 1

    # Add the days in the previous months
    month -= 1
    while month > 0:
        day = day + days[month - 1]
        month -= 1
    return day


bot.run(TOKEN)
